name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.3.2
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.19.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.6
  emoji_picker_flutter: ^2.2.0
  http: ^1.2.1
  html: ^0.15.4
  any_link_preview: ^3.0.2
  progress_indicators: ^1.0.0
  image_picker: ^1.1.1
  audio_waveforms: ^1.0.5
  # For formatting time locale in message receipts
  timeago: ^3.6.1
  voice_message_package: ^2.2.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

